### ISSUE TITLE
For audio pulseaudio backend needs pactl tool from pulseaudio-utils (on Debian)

### ISSUE THREAD

**Issue by yarikoptic** [wieluk/psychopy_linux_installer#38]
Otherwise we would get the following error message 

```
❯ rm output*log; singularity exec ./repronim-psychopy--2024.1.4.sing ~/proj/repronim/reprostim/tools/reprostim-timesync-stimuli output2.log 1
2024-11-06 12:54:22,823 [INFO] reprostim-timesync-stimuli script started
2024-11-06 12:54:27,197 [INFO] main script started
2024-11-06 12:54:28,374 [DEBUG] warming time: 5.589591 sec
2024-11-06 12:54:28,374 [DEBUG] play_beep(480, duration=120, volume=1.0)
sh: 1: pactl: not found
sh: 1: pactl: not found
PTB-CRITICAL: In call to PsychSetThreadPriority(): Failed to set new basePriority 2, tweakPriority 4, effective 4 [REALTIME] for thread (nil) provided!
PTB-WARNING: In PsychPortAudio:paCallback(): Failed to switch to boosted realtime priority [Operation not permitted]! Audio may glitch.
^CTraceback (most recent call last):
  File "/home/yoh/proj/repronim/reprostim/tools/reprostim-timesync-stimuli", line 125, in <module>
    play_beep(480, 120, 1.0)
  File "/home/yoh/proj/repronim/reprostim/tools/reprostim-timesync-stimuli", line 81, in play_beep
    core.wait(duration)  # Wait for the beep to finish
  File "/opt/psychopy/psychopy_2024.1.4_py_3.10.14/lib/python3.10/site-packages/psychopy/clock.py", line 586, in wait
    time.sleep(sleepDur)
KeyboardInterrupt
sh: 1: pactl: not found
sh: 1: pactl: not found
3.6044 	WARNING 	Monitor specification not found. Creating a temporary one...
3.6091 	WARNING 	Requested an unavailable screen number - using first available.
3.6560 	WARNING 	User requested fullscreen with size [800 600], but screen is actually [3840, 2400]. Using actual size

```

FWIW that singularity image was created using this recipe https://github.com/ReproNim/containers/blob/master/images/repronim/Singularity.repronim-psychopy--2024.1.4
which was produced using NeuroDocker (https://github.com/ReproNim/neurodocker) using the invocation in this script:
https://github.com/ReproNim/containers/blob/master/images/repronim/repronim-psychopy.sh#L19 .

**Comment by yarikoptic** [comment]
Thank you!  Let's close then

well, for me audio doesn't work at all ;)  so you must be ahead of me overall.

Are you interested in containers at all?
